"""Agregar datos de contacto y perfil a usuarios

Revision ID: 2907241e9078
Revises: 2e4f6104c624
Create Date: 2026-09-20 09:15:21.919030

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2907241e9078'
down_revision: Union[str, Sequence[str], None] = '2e4f6104c624'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone', sa.String(length=30), nullable=True))
    op.add_column('users', sa.Column('professional_license', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('specialty', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('avatar_path', sa.String(length=500), nullable=True))
    op.add_column('users', sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_login_at')
    op.drop_column('users', 'avatar_path')
    op.drop_column('users', 'specialty')
    op.drop_column('users', 'professional_license')
    op.drop_column('users', 'phone')
    # ### end Alembic commands ###
