"""Relacionar sesiones clinicas con citas

Revision ID: 2a1ef4522be1
Revises: cab706a6ece5
Create Date: 2026-09-25 13:00:18.545852

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a1ef4522be1'
down_revision: Union[str, Sequence[str], None] = 'cab706a6ece5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clinical_sessions', sa.Column('appointment_id', sa.Uuid(), nullable=True))
    op.create_foreign_key('fk_clinical_sessions_appointment_id', 'clinical_sessions', 'appointments',['appointment_id'], ['id'], ondelete='SET NULL',)
    op.create_unique_constraint('uq_clinical_sessions_appointment_id', 'clinical_sessions', ['appointment_id'],)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint('uq_clinical_sessions_appointment_id', 'clinical_sessions', type_='unique',)
    op.drop_constraint('fk_clinical_sessions_appointment_id', 'clinical_sessions', type_='foreignkey',)
    op.drop_column('clinical_sessions', 'appointment_id')
    # ### end Alembic commands ###
