"""agregar pacientes

Revision ID: c5a897ae38e6
Revises: e40a749b23ce
Create Date: 2026-09-21 13:15:01.749495

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c5a897ae38e6'
down_revision: Union[str, Sequence[str], None] = 'e40a749b23ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patients',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('professional_id', sa.UUID(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('identification', sa.String(length=50), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(),server_default=sa.true(),nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True),server_default=sa.func.now(),nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True),server_default=sa.func.now(), nullable=False),
    sa.ForeignKeyConstraint(['professional_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patients_professional_id'), 'patients', ['professional_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_patients_professional_id'), table_name='patients')
    op.drop_table('patients')
    # ### end Alembic commands ###
