"""add clinical session notes

Revision ID: db966ef4207d
Revises: 2a1ef4522be1
Create Date: 2026-10-01 16:07:09.075430

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db966ef4207d'
down_revision: Union[str, Sequence[str], None] = '2a1ef4522be1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clinical_session_notes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('clinical_session_id', sa.Uuid(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['clinical_session_id'], ['clinical_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clinical_session_notes_clinical_session_id'), 'clinical_session_notes', ['clinical_session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_clinical_session_notes_clinical_session_id'), table_name='clinical_session_notes')
    op.drop_table('clinical_session_notes')
    # ### end Alembic commands ###
